# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classification.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63lassification.proto\"1\n\x1aImageClassificationRequest\x12\x13\n\x0bimage_bytes\x18\x01 \x01(\x0c\"h\n\x14\x43lassificationResult\x12\x12\n\nclass_name\x18\x01 \x01(\t\x12\x10\n\x08\x63lass_id\x18\x02 \x01(\x05\x12\x16\n\x0e\x63lass_metadata\x18\x03 \x01(\t\x12\x12\n\nconfidence\x18\x04 \x01(\x02\"@\n\x16\x43lassificationResponse\x12&\n\x07results\x18\x01 \x03(\x0b\x32\x15.ClassificationResult2W\n\x0e\x43lassification\x12\x45\n\rClassifyImage\x12\x1b.ImageClassificationRequest\x1a\x15.ClassificationResult\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'classification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGECLASSIFICATIONREQUEST']._serialized_start=24
  _globals['_IMAGECLASSIFICATIONREQUEST']._serialized_end=73
  _globals['_CLASSIFICATIONRESULT']._serialized_start=75
  _globals['_CLASSIFICATIONRESULT']._serialized_end=179
  _globals['_CLASSIFICATIONRESPONSE']._serialized_start=181
  _globals['_CLASSIFICATIONRESPONSE']._serialized_end=245
  _globals['_CLASSIFICATION']._serialized_start=247
  _globals['_CLASSIFICATION']._serialized_end=334
# @@protoc_insertion_point(module_scope)
