# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embedding.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65mbedding.proto\",\n\x15ImageEmbeddingRequest\x12\x13\n\x0bimage_bytes\x18\x01 \x01(\x0c\"$\n\x14TextEmbeddingRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"(\n\tEmbedding\x12\x0e\n\x06values\x18\x01 \x03(\x02\x12\x0b\n\x03\x64im\x18\x02 \x01(\x05\x32x\n\x10\x45mbeddingService\x12\x32\n\nEmbedImage\x12\x16.ImageEmbeddingRequest\x1a\n.Embedding\"\x00\x12\x30\n\tEmbedText\x12\x15.TextEmbeddingRequest\x1a\n.Embedding\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEEMBEDDINGREQUEST']._serialized_start=19
  _globals['_IMAGEEMBEDDINGREQUEST']._serialized_end=63
  _globals['_TEXTEMBEDDINGREQUEST']._serialized_start=65
  _globals['_TEXTEMBEDDINGREQUEST']._serialized_end=101
  _globals['_EMBEDDING']._serialized_start=103
  _globals['_EMBEDDING']._serialized_end=143
  _globals['_EMBEDDINGSERVICE']._serialized_start=145
  _globals['_EMBEDDINGSERVICE']._serialized_end=265
# @@protoc_insertion_point(module_scope)
