# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import embedding_pb2 as embedding__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in embedding_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class EmbeddingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EmbedImage = channel.unary_unary(
                '/EmbeddingService/EmbedImage',
                request_serializer=embedding__pb2.ImageEmbeddingRequest.SerializeToString,
                response_deserializer=embedding__pb2.Embedding.FromString,
                _registered_method=True)
        self.EmbedText = channel.unary_unary(
                '/EmbeddingService/EmbedText',
                request_serializer=embedding__pb2.TextEmbeddingRequest.SerializeToString,
                response_deserializer=embedding__pb2.Embedding.FromString,
                _registered_method=True)


class EmbeddingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EmbedImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EmbedImage': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedImage,
                    request_deserializer=embedding__pb2.ImageEmbeddingRequest.FromString,
                    response_serializer=embedding__pb2.Embedding.SerializeToString,
            ),
            'EmbedText': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedText,
                    request_deserializer=embedding__pb2.TextEmbeddingRequest.FromString,
                    response_serializer=embedding__pb2.Embedding.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'EmbeddingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('EmbeddingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmbeddingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EmbedImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EmbeddingService/EmbedImage',
            embedding__pb2.ImageEmbeddingRequest.SerializeToString,
            embedding__pb2.Embedding.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/EmbeddingService/EmbedText',
            embedding__pb2.TextEmbeddingRequest.SerializeToString,
            embedding__pb2.Embedding.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
